<?php
return [
    'supportEmail'                  => 'admin@bigbiz.pp.ua',
    'adminEmail'                    => 'admin@bigbiz.pp.ua',
    'user.passwordResetTokenExpire' => 3600,
    'default_rest_api_limit'        => 5,
    's3_folders'                    => [
        'user_profile' => 'user_profile',
        'shop_profile' => 'shop_profile'
    ],
    // count of items per page
    'shopsPerPage'            => 8,
    'productsPerPage'         => 12,
    'themesPerPage'           => 6,
    'reviewsPerPage'          => 6,
    'productFeedbacksPerPage' => 5,
    // min-max size for upload images
    'theme_image_max_size'      => 1024 * 1024 * 5,
    'theme_image_min_size'      => 1024 * 100,
    'mobile_banner_max_size'    => 1024 * 1024 * 5,
    'mobile_banner_min_size'    => 1024 * 100,
    'product_image_max_size'    => 1024 * 1024 * 5,
    'product_image_min_size'    => 1024 * 100,
    'website_banner_max_size'   => 1024 * 1024 * 5,
    'website_banner_min_size'   => 1024 * 100,
    'product_image_min_width'   => 1080,
    'product_image_min_height'  => 640,
    'product_image_max_width'   => 3840,
    'product_image_max_height'  => 2160,
    'theme_image_min_width'     => 1080,
    'theme_image_min_height'    => 640,
    'theme_image_max_width'     => 3840,
    'theme_image_max_height'    => 2160,
    'mobile_banner_min_width'   => 1080,
    'mobile_banner_min_height'  => 640,
    'mobile_banner_max_width'   => 3840,
    'mobile_banner_max_height'  => 2160,
    'website_banner_min_width'  => 1080,
    'website_banner_min_height' => 640,
    'website_banner_max_width'  => 3840,
    'website_banner_max_height' => 2160,
];
